# Generated by Django 2.2.11 on 2020-03-07 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_remove_evento_convidado'),
        ('convidado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidado',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evento.Evento'),
            preserve_default=False,
        ),
    ]
