# Generated by Django 2.2.11 on 2020-03-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_remove_evento_convidado'),
        ('convidado', '0002_convidado_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convidado',
            name='evento',
        ),
        migrations.AddField(
            model_name='convidado',
            name='evento',
            field=models.ManyToManyField(to='evento.Evento'),
        ),
    ]
