# Generated by Django 2.2.11 on 2020-03-13 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convidado', '0006_convidado_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidado',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
