# Generated by Django 2.2.11 on 2020-03-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convidado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_festa', models.CharField(max_length=150)),
                ('data', models.DateField()),
                ('local', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=200)),
                ('convidado', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='convidado.Convidado')),
            ],
        ),
    ]
