# Generated by Django 2.2.11 on 2020-03-14 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0007_auto_20200314_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
